name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "dev"

env:
  FRONTEND_IMAGE: registry.digitalocean.com/tworocksstudio-registry/app-center/portal
  BACKEND_IMAGE: registry.digitalocean.com/tworocksstudio-registry/app-center/backend

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'apps/web/**'
            backend:
              - 'apps/api/**'

  build-image:
    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short $GITHUB_SHA)"
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build Frontend image
        if: needs.changes.outputs.frontend == 'true'
        run: docker build -f ./apps/web/Dockerfile . -t ${{ env.FRONTEND_IMAGE }}:${{ steps.sha.outputs.sha }}
      - name: Build Backend image
        if: needs.changes.outputs.backend == 'true'
        run: docker build -f ./apps/api/Dockerfile . -t ${{ env.BACKEND_IMAGE }}:${{ steps.sha.outputs.sha }}
      - name: Log in to DigitalOcean Container Registry
        if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.backend == 'true' }}
        run: doctl registry login --expiry-seconds 1200
      - name: Push Frontend image
        if: needs.changes.outputs.frontend == 'true'
        run: docker push ${{ env.FRONTEND_IMAGE }}:${{ steps.sha.outputs.sha }}
      - name: Push Backend image
        if: needs.changes.outputs.backend == 'true'
        run: docker push ${{ env.BACKEND_IMAGE }}:${{ steps.sha.outputs.sha }}

  update-helm-chart:
    needs: build-image
    runs-on: ubuntu-latest
    if: ${{ needs.build-image.outputs.sha != '' }}
    steps:
      - name: Checkout Helm chart repository from GitLab
        run: |
          git clone https://kelvin.kwong:${{ secrets.GITLAB_PRIVATE_KEY }}@gitlab.2rocksstudio.hk/devops/dg-argocd.git

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Set branch name
        id: set-branch
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "::set-output name=branch::main"
          elif [[ ${{ github.ref }} == 'refs/heads/uat' ]]; then
            echo "::set-output name=branch::uat"
          elif [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
            echo "::set-output name=branch::dev"
          else
            echo "::error ::Invalid branch name"
            exit 1
          fi

      - name: Update Backend Helm chart image.tag value
        run: |
          cd dg-argocd/app-center/backend-helm
          yq eval '.image.tag = "${{ needs.deploy.outputs.sha }}"' -i values.${{ steps.set-branch.outputs.branch }}.yaml

      - name: Update Frontend Helm chart image.tag value
        run: |
          cd dg-argocd/app-center/portal-helm
          yq eval '.image.tag = "${{ needs.deploy.outputs.sha }}"' -i values.${{ steps.set-branch.outputs.branch }}.yaml

      - name: Commit and push changes to Helm chart repository
        run: |
          cd dg-argocd
          git config --global user.email "github-actions@2rocksstudio.hk"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update image.tag to ${{ needs.deploy.outputs.sha }} for ${{ steps.set-branch.outputs.branch }} branch"
          git push origin main
