name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'dev'

env:
  FRONTEND_IMAGE: registry.digitalocean.com/two-rocks-studio/app-center/portal
  BACKEND_IMAGE: registry.digitalocean.com/two-rocks-studio/app-center/backend

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'apps/portal/**'
            backend:
              - 'apps/backend/**'

  build:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install
        if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.backend == 'true' }}
      - name: Build Frontend
        if: needs.changes.outputs.frontend == 'true'
        run: pnpm nx build portal --verbose
      - name: Build Backend
        if: needs.changes.outputs.backend == 'true'
        run: pnpm nx build backend --verbose
      - name: Cache Frontend Build
        if: needs.changes.outputs.frontend == 'true'
        uses: actions/cache@v4
        with:
          path: ./dist/apps/portal
          key: ${{ runner.os }}-frontend-build-${{ github.sha }}
      - name: Cache Backend Build
        if: needs.changes.outputs.backend == 'true'
        uses: actions/cache@v4
        with:
          path: ./dist/apps/backend
          key: ${{ runner.os }}-backend-build-${{ github.sha }}

  deploy:
    needs: [changes, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Frontend Build
        if: needs.changes.outputs.frontend == 'true'
        uses: actions/cache@v4
        with:
          path: ./dist/apps/portal
          key: ${{ runner.os }}-frontend-build-${{ github.sha }}
      - name: Download Backend Build
        if: needs.changes.outputs.backend == 'true'
        uses: actions/cache@v4
        with:
          path: ./dist/apps/backend
          key: ${{ runner.os }}-backend-build-${{ github.sha }}
      - name: Generate SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short $GITHUB_SHA)"
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build Frontend image
        if: needs.changes.outputs.frontend == 'true'
        run: docker build -f ./apps/portal/Dockerfile . -t ${{ env.FRONTEND_IMAGE }}:${{ steps.sha.outputs.sha }}
      - name: Build Backend image
        if: needs.changes.outputs.backend == 'true'
        run: docker build -f ./apps/backend/Dockerfile . -t ${{ env.BACKEND_IMAGE }}:${{ steps.sha.outputs.sha }}
      - name: Log in to DigitalOcean Container Registry
        if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.backend == 'true' }}
        run: doctl registry login --expiry-seconds 1200
      - name: Push Frontend image
        if: needs.changes.outputs.frontend == 'true'
        run: docker push ${{ env.FRONTEND_IMAGE }}:${{ steps.sha.outputs.sha }}
      - name: Push Backend image
        if: needs.changes.outputs.backend == 'true'
        run: docker push ${{ env.BACKEND_IMAGE }}:${{ steps.sha.outputs.sha }}
